### ISSUE TITLE
Hosting the site

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#11]
@MattBlissett @timrobertson100 is there a compelling reason to host the TDWG website on a GBIF server, rather than GitHub Pages?

Advantages I see with GitHub pages:
- Already used for DwC, AC, Camtrap DP and other TDWG satellite website
- Jekyll theme will be used by the satellite websites too, so it has to work with GitHub Pages anyway
- Feedback that the site is building (i.e. the yellow dot or green check)
- Still possible to have custom domain
- Still possible to setup redirects?

**Comment by MattBlissett** [comment]
Are HTTP redirects possible? I see workarounds, but I'm not aware of a way to have redirects.

Jenkins supports the yellow/green/red dot, it's just not been enabled.

https://github.com/tdwg/infrastructure/blob/master/httpd/www.tdwg.org.conf#L54-L82

**Comment by stanblum** [comment]
The feedback that Jenkins provides is really important when someone
attempts an edit/addition and the results don't render.  We had a case
earlier this year during conference preparation, when updating is critical,
and new content jammed up the building system.  Jenkins (?) was critical in
revealing where the problem was and enabling me to get the site working
again.

**Comment by peterdesmet** [comment]
@MattBlissett I'll let you take a decision on this.

**Comment by MattBlissett** [comment]
I've set up https://dev.tdwg.org/ building from this repository.

I want to look at it in more detail tomorrow, as the builds seem to be much slower than they should be -- the Jekyll Docker container isn't caching installed Gems, and is messing about with permissions which slow it down.

**Comment by MattBlissett** [comment]
It's now taking about 1 minute to build on Jenkins. This is slower than the Python site, but hopefully not too much of problem.

**Comment by peterdesmet** [comment]
Thanks for looking into this @MattBlissett I wonder if it’s going to take longer if I add more pages …

**Comment by peterdesmet** [comment]
Build time should now be lower again (I'm getting 16 seconds locally).

**Comment by peterdesmet** [comment]
The build is done by Jenkins at https://builds.gbif.org/job/tdwg-website/
