### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#12]
The current website uses breadcrumbs on every page:

<img width="433" alt="Screenshot 2022-11-14 at 18 16 35" src="https://user-images.githubusercontent.com/600993/201724092-95b01900-23b2-4a44-97ca-c1f5fa6191c6.png">

The Jekyll website does not.

Reimplementing breadcrumbs is possible, but would require some development work. I would first like to see if they are missed. ☺️

**Comment by stanblum** [comment]
That manual menu system might make up for the lack of breadcrumbs, but I
don't know yet how menus are managed and what options we have.  What would
be frustrating is to be a few levels deep somewhere (e.g., info about a
conference, and have no way to back up one or two levels to get to sibling
or "cousin" pages except going all the way to the top.  But I think we
don't need huge depth, and the menus at the top of deeper pages can be
customized to provide easy navigation to related pages.

**Comment by peterdesmet** [comment]
@stanblum this is how menus are managed (example with annotation) https://github.com/peterdesmet/petridish/blob/main/_data/navigation.yml I hope it is rather self explanatory.

Here's the current menu for the Jekyll site: https://github.com/tdwg/website-jekyll/blob/main/_data/navigation.yaml

**Comment by stanblum** [comment]
I will have to pick this up AFTER the filings are done.

**Comment by gkampmeier** [comment]
@peterdesmet I use the breadcrumbs to go back to the main page.  That said, I think the menus can work, mostly, except that we're missing a layer in the menus for the context (e.g., [https://tdwg.github.io/website-jekyll/conferences/2022/](https://tdwg.github.io/website-jekyll/conferences/2022/) has no way to get back to TDWG 2021 or any other year w/o going through the root of tdwg.org

**Comment by peterdesmet** [comment]
> has no way to get back to TDWG 2021 or any other year w/o going through the root of tdwg.org

@gkampmeier that is indeed correct, but that's maybe not too problematic?

**Comment by stanblum** [comment]
I think Gail might be the only one who routinely does comparisons between
conference years; i.e., when building this year's conference, she looks at
the past year a lot.  One way to get around the loss of breadcrumbs would
be to have two tabs/windows open; one to previous year, one to this year.
Would that work?

**Comment by gkampmeier** [comment]
@stanblum and @peterdesmet yeah, that's OK.
