### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#13]
The current website has search functionality: https://www.tdwg.org/search.html?q=darwin+core

<img width="772" alt="Screenshot 2022-11-14 at 18 20 06" src="https://user-images.githubusercontent.com/600993/201724785-74709286-6d77-464b-af05-62b838c81535.png">

The Jekyll website does not.

Reimplementing search is likely possible (see e.g. https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/), but would require some development work. @stanblum do we have usage stats on the search functionality? Would it be missed?

**Comment by stanblum** [comment]
As far as I know we don't have usage statistics of any kind.  My sense is
that search is rarely used.  But I have used it in the past if I have
forgotten where rarely used information is, or to see if we have the right
information posted at all.  Is something posted in both standards and
community?  Maybe Google search is good enough.

I don't have a strong opinion on the utility of Search.

**Comment by gkampmeier** [comment]
@peterdesmet I personally get frustrated when I find a site without a search, however, I do remember an early lesson in user interface design: if the user feels they have to search for your content, you have failed in your design.  So if we can make a site where the user can easily locate what s/he wants, then we can work without it, but the very fact that Darwin Core is mentioned in 73 places points out that this is likely not the case.

**Comment by peterdesmet** [comment]
I don't have the time to implement a search right now.
