### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by gkampmeier** [tdwg/website-jekyll#16]
@peterdesmet we need to add a link to the [Code of Conduct ](https://www.tdwg.org/about/code-of-conduct/) in the footer. Arguably the [TDWG Diversity & Inclusion statement](https://www.tdwg.org/about/diversity-inclusion/) should also be linked in the footer.

**Comment by gkampmeier** [comment]
Also, we have a Facebook page [https://www.facebook.com/groups/326780777736](https://www.facebook.com/groups/326780777736)

**Comment by peterdesmet** [comment]
Diversity and inclusion now added https://tdwg.github.io/website-jekyll/

Should the Facebook page be one of the logos like Twitter?

**Comment by gkampmeier** [comment]
Probably. I am an admin on the FB page and we post news there, although rarely are there discussions.  The audience is iffy (many first time contributors see biodiversity but not standards), but probably reaches some not reached elsewhere.

**Comment by peterdesmet** [comment]
The facebook link is now included in the footer.
