### ISSUE TITLE
Provide better versions of some TDWG logos

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#23]
@stanblum most of the new TDWG logos (https://www.tdwg.org/about/logos/) are provided nicely cropped, both in png and svg. Except for:

https://static.tdwg.org/logo/Colour/SVG/TDWG-Logo_Hex-Sticker_frame_blue.svg
https://static.tdwg.org/logo/White/SVG/TDWG-Logo_Short-Form-white.svg
https://static.tdwg.org/logo/White/SVG/TDWG-Logo_Hex-Sticker-white_transp_frame.svg

These have lots of padding and Illustrator metadata.

Is it possible to get those in crisp versions like the others?

**Comment by ben-norton** [comment]
I can tackle that if needed.

**Comment by stanblum** [comment]
Did you find that some were strangely pixelated?  I didn't have the time or
tools to sort that out, so I would definitely appreciate it if you fix
those.   If you put them in the "Outreach and Communications" Google Drive,
I'll copy them over to the static server.  I'll email you the link
separately.

**Comment by peterdesmet** [comment]
> Did you find that some were strangely pixelated?

No, just lots of padding and metadata. Compare the code and display of:

- Good: https://static.tdwg.org/logo/Colour/SVG/TDWG-Logo_Short-Form.svg (code is minimized, logo has no padding)
- Bad: https://static.tdwg.org/logo/White/SVG/TDWG-Logo_Short-Form-white.svg (code is verbose, logo has lots of padding - use a black background to actually see: `style="background: black;"`)

@ben-norton if you could fix that, that would be great!

**Comment by ben-norton** [comment]
Sent to Stan.

**Comment by stanblum** [comment]
Matt Blissett sorted the permissions issue for me (Thanks @MattBlissett !).  I replaced the SVG for: 
TDWG-Logo_Short-Form-white.svg 

Still need to see about others that need to be replaced...

**Comment by peterdesmet** [comment]
@stanblum can this issue be closed?

**Comment by stanblum** [comment]
Not just yet.  I need to look at the other SVGs and see if they need to
have the padding adjusted.

**Comment by ben-norton** [comment]
@stanblum Thanks Stan. Let me know if anything I sent you is problematic.

**Comment by stanblum** [comment]
Hi Ben,

The only one I'm missing and still has problems is this one.

Color:
TDWG-Logo_Hex-Sticker_frame_blue.svg:   original has excessive padding

The last one you sent didn't render correctly -- the individual element
positions had been scrambled.


I replaced the white horizontal short form last week I think, but I still
need to do this one.

White:
TDWG-Logo_Hex-Sticker-white_transp_frame.svg:  excessive padding

Fortunately, the last version you sent me does render correctly, though, so
I just need to replace that bad with the good...  Which I will do,
straightaway.


So, again, the only one I need revised from you is the first one above.

Thanks again for helping to straighten these out.

-Stan

**Comment by ben-norton** [comment]
I'll do it tonight. :)

**Comment by ben-norton** [comment]
![TDWG-Logo_Hex-Sticker_frame_blue_no-padding](https://user-images.githubusercontent.com/7331520/204961659-613d5a70-754a-4e6a-ba35-fe6e6d9994a7.svg)

**Comment by ben-norton** [comment]
I created two. The version above has the padding removed. The second file (linked below) is a simplified version of the first. The SVG has a few deprecated attributes that can be removed. If downloading the SVG above is problematic, I've shared both via google drive.
Padding Removed: https://drive.google.com/file/d/1TvsBlTinuWLoGS_VXaHaHtq4LQPORNH7/view?usp=sharing
Padding Removed and Simplified: https://drive.google.com/file/d/1VyBzyaI-Eie0RD0Kxw8CkBpMadJH3BP4/view?usp=sharing

**Comment by stanblum** [comment]
I was able to save the one displayed two notes above.  I have the previous one on my system with a new name  (..._padded), and I uploaded the fixed one using the original name -- i.e., the same link points to the updated file.  I couldn't access the simplified file -- requested access.  I'm going to close this issue.
