### ISSUE TITLE
Navigation for TDWG conference 2022

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#24]
@gkampmeier The TDWG 2022 conference has many subpages and would benefit from its own top navigation (as suggested in #7). I made created a first attempt at https://tdwg.github.io/website-jekyll/conferences/2022/

Below the current pages, their current title and my suggested navigation.

- [ ] Can you review the navigation and make suggestions. Note that we can make use of dropdowns, subheaders in dropdowns and dividers to separate content in dropdowns
- [ ] I have shorted some titles for brevity and would use the same titles as the page titles (e.g. dropping `TDWG 2022 - ` prefix as it will now be clearer that the page is part of TDWG). Some other information can go in the page description/summary if needed
- [ ] Is there a rule on regular vs title case for TDWG website pages?

## Current pages

path | current title | suggested navigation
--- | --- | ---
[/](https://www.tdwg.org/conferences/2022/) | TDWG 2022 - a Hybrid Conference | TDWG 2022
Dropdown | - | Submissions
Subheader | - | - Abstracts
[/call-for-abstracts](https://www.tdwg.org/conferences/2022/call-for-abstracts) | TDWG 2022 - Call for Abstracts | - Call for abstracts
[/instructions-for-abstract-submission](https://www.tdwg.org/conferences/2022/instructions-for-abstract-submission) | Instructions for Abstract Submission | - Instructions for abstract submission
[/instructions-for-editors](https://www.tdwg.org/conferences/2022/instructions-for-editors) | Instructions for Editors | - Instructions for editors
[/presentation-info](https://www.tdwg.org/conferences/2022/presentation-info) | Presentation Information | - Instructions for presentations
Divider | - | - ---
[/call-for-organized-sessions](https://www.tdwg.org/conferences/2022/call-for-organized-sessions) | TDWG 2022 - call for organized sessions | - Organized sessions
Dropdown | - | Program
[/full-schedule](https://www.tdwg.org/conferences/2022/full-schedule) | Full Schedule | - Full schedule
[/session-list](https://www.tdwg.org/conferences/2022/session-list) | Symposia, Workshops, & Discussion Sessions | - Sessions
[/keynotes](https://www.tdwg.org/conferences/2022/keynotes) | Keynote Speakers | - Keynote speakers
[/posters](https://www.tdwg.org/conferences/2022/posters) | Posters for TDWG 2022 | - Posters
Divider | --- | - ---
[/program-committee](https://www.tdwg.org/conferences/2022/program-committee) | Program Committee | - Program committee
[/working-sessions](https://www.tdwg.org/conferences/2022/working-sessions) | TDWG 2022 - Working Sessions | Working sessions
[/local-info](https://www.tdwg.org/conferences/2022/local-info) | Attend TDWG 2022 In Person! | Local information

**Comment by peterdesmet** [comment]
Note: we'll have to do the same for TDWG 2020 and 2021, but I think it's more efficient to settle on a navigation for one and to then reuse that for the others

**Comment by ben-norton** [comment]
100%. Has anyone reviewed the conference pages to determine what must be kept and what can be dropped? I suggest we only retain the critical information, the really important content that's relevant to someone 2-5 years from now. That should simplify the navigation and may even change it.

**Comment by gkampmeier** [comment]
@peterdesmet I like the navigation although I'm wondering if 

/submissions
../Instructions
Divider
../Calls  --could also be "solicitations" but this is longer and more arcane

- [x] The calls are the most ephemeral and are included for easy reference when corresponding with those who missed the email or promoting on social media.  The instructions will eventually also become moot (the 2-5 yr timeline mentioned by @ben-norton, and no we haven't reviewed these pages, but it is only the last three years that so much information has been documented on the conference pages).  However, it would be nice to have a way to archive pages (likely another issue? and one of interest for other portions of the website)...?

- [x] The **Program** dropdown gives a single link to the full schedule††. Given that several permutations are/were made available as they were confirmed [https://tdwg.github.io/website-jekyll/conferences/2022/#schedule](https://tdwg.github.io/website-jekyll/conferences/2022/#schedule), this link should either point to the options in the main document OR to one of the final documents listed there. The current problem is that all of these live somewhere on Google Drive and risk being swept away or the links broken. This points to an issue of the static server and its accessibility/use (probably should be a separate issue).

- [x] The **program** dropdown should include a link to the abstract volume (aka "TDWG Proceedings" followed by the year).  Here [https://biss.pensoft.net/collection/384/](https://biss.pensoft.net/collection/384/) and a place for the session videos on TDWG's YouTube Channel (these are not yet public).  

- [x] **Working sessions** will also need to be a dropdown with a link to the session page as one option and a link to the YouTube videos when they become available.

- [x] **Local information** might be better categorized as "Logistics", so as to encompass virtual attendees as well as in-person information.  While we currently have one page there, in the future, we might reduce the length of the opening page (and of [this one](https://tdwg.github.io/website-jekyll/conferences/2022/local-info/) by creating shorter pages that are more to the point.  

†† This particular rendition of the full schedule is a harder-to-read version of [https://static.tdwg.org/conferences/2022/full-schedule-w-local-time.html](https://static.tdwg.org/conferences/2022/full-schedule-w-local-time.html).  I know this is not what you were asking for here (organizational aspects) but there are a few things that could be improved for legibility: suffers from lack of table grid) and the fact that those presenting in-person were not highlighted with color to pull them out. What is likely good, however, is that it is editable (cf., static server issues) (e.g., there was a mistake in the timing of the closing session and a few other changes made on the fly during the conference).

**Comment by peterdesmet** [comment]
@gkampmeier I have done the requested changes (not on website-jekyll, but in branch of main website) except for the items you mentioned should be separate issues.

I don't understand what you mean by the following however:

```
/submissions
../Instructions
Divider
../Calls --could also be "solicitations" but this is longer and more arcane
```

Are there items you want to change on this submenu?

<img width="278" alt="Screenshot 2022-12-03 at 16 27 17" src="https://user-images.githubusercontent.com/600993/205448689-a5815dc6-bb27-4872-b25e-99baf207ec26.png">

**Comment by gkampmeier** [comment]
@peterdesmet what I meant was that the submissions could be divided into not \'abstracts\' and \'organized sessions\' but \'Instructions\' and \'Calls\'.

### Instructions 
- Abstract submission
- Editors
- Presentations
----
### Calls
- Abstracts 
- Organized sessions

Meaning that both of the headers are implied for the stuff following. Can also be \'Instructions for\' and \'Calls for\' to make it even clearer, but eliminates the need for longer, repetitive titles.

P.S. It is obvious I am still struggling with what I see here in preview while I'm writing and what the final product will be

**Comment by peterdesmet** [comment]
This has now been implemented for all conferences with more than one page, see e.g. https://dev.tdwg.org/conferences/2022/
