### ISSUE TITLE
Crop images of people

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#28]
I'm using the `team` layout for keynote speakers, executive committee members, programme committee members. One requirement however is that the images should have the same height and width (see stretched image of Elycia Wallis below).

I cannot edit the images, as they are stored on static.tdwg.org. @stanblum or @MattBlissett can you crop these to squares (using the largest dimension)? Note: many of these are already square.

- [x] https://static.tdwg.org/conferences/2022/pc/barve-vijay.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/chapman-cat.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/earl-chandra.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/gaikwad-jitendra.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/james-shelley.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/kampmeier-gail.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/loo-tina.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/penev-lyubomir.jpg
- [x] https://static.tdwg.org/conferences/2022/pc/wallis-ely.jpg
- [x] https://static.tdwg.org/conferences/2022/images/richard-pyle-640.jpg
- [x] https://static.tdwg.org/conferences/2022/images/debora-pignatari-drucker-h640.jpg
- [x] https://static.tdwg.org/conferences/2022/images/theary-ung-cropped-640.jpg
- [x] https://static.tdwg.org/conferences/2022/images/pavel-stoev-640.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/barve-vijay.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/brosens-dimi.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/cook-kimberly.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/earl-chandra.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/gadelha-luiz.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/james-shelley.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/johadien-rukaya.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/kampmeier-gail.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/loo-tina.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/shashkov.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/ung-theary.jpg
- [x] https://static.tdwg.org/conferences/2021/images/pc/weiland-claus.jpg

![Program-Committee-TDWG](https://user-images.githubusercontent.com/600993/205889626-d8d24184-a645-410b-baba-9cf2328e0df4.png)

**Comment by MattBlissett** [comment]
Note you have access to the server. You gave me an SSH key a while ago.

**Comment by stanblum** [comment]
Hi Peter,

I've created and uploaded square images for the ones that were not.  New
files are:

static.tdwg.org/conferences/2022/images/ :
debora-pignatari-drucker-sqr.jpg
pavel-stoev-sqr.jpg
richard-pyle-sqr.jpg
theary-ung-sqr.jpg

I replaced the images in the program committee (pc) folder, so the
file-names referenced in markdown don't need to be modified.
static.tdwg.org/conferences/2022/pc/

The circular images look nice!

Thanks!

-Stan

**Comment by peterdesmet** [comment]
Thanks Stan. The https://static.tdwg.org/conferences/2022/pc/wallis-ely.jpg is still incorrect: it was cropped, but is not square. Can you correct this?

**Comment by stanblum** [comment]
Sorry! Try now?

**Comment by stanblum** [comment]
Also saw that Kimberly Cook's photo wasn't edited/uploaded correctly, but
re-did that one, too.

**Comment by peterdesmet** [comment]
Thanks!

**Comment by peterdesmet** [comment]
@stanblum can you also do the confererence/2021 images (todo list updated above)?

**Comment by stanblum** [comment]
All 2021 program committee images cropped to square.
