### ISSUE TITLE
Monitor build time

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#3]
Remarked by @stanblum:

> difference in build speed?  (currently it takes about 1-2 mins; it would be unfortunate to have that increase significantly.)

**Comment by MattBlissett** [comment]
Jenkins reports 12-20 seconds: https://builds.gbif.org/job/tdwg-website/buildTimeTrend so the rest of the time is probably Github sending the notification of changes to Jenkins, and Jenkins pausing a few seconds (in case of further changes) before starting.

**Comment by peterdesmet** [comment]
Local build time is around 15 seconds, @MattBlissett didn't indicate Jenkins build time issues. Closing this issue.
