### ISSUE TITLE
Required content changes to make use of default template

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#4]
Content changes to make use of the new Jekyll templates

- [x] Rename `summary` to `decription`
- [x] Rename `cover_image` to `background: img`
- [x] Rename `cover_image_by` to `background: by`
- [x] Rename `cover_image_ref` to `background: href`
- [x] Remove `tags`
- [x] Remove `page_order`
- [x] Make sure headings start at h2
- [x] Update internal links from `{filename}` to direct permalink or `| relative_url`
- [x] Wrap links in `<...>` (or set `markdown: gfm` in _config.yml, but that doesn't allow styling)
- [x] Check for unreadable characters

**Comment by stanblum** [comment]
Is there no way to force page order in Jekyll?

**Comment by peterdesmet** [comment]
Definitely possible to have page order in Jekyll, but we would have to see if/where it is necessary.

**Comment by stanblum** [comment]
We use page-order on /about/, and also under every conference, ordering the
contained pages by importance (at the time).

**Comment by gkampmeier** [comment]
@peterdesmet is there a replacement concept for tags?  We don't currently have a good list of keywords (that I know of) used for these, but that also may account for lack of good use for this type of feature.

**Comment by peterdesmet** [comment]
All required changes in the metadata have been applied. @gkampmeier as mentioned in https://github.com/tdwg/website-jekyll/issues/5#issuecomment-1412556300, tags are no longer used to organize content. Except news articles, where tags can be used to filter: https://dev.tdwg.org/news/?tag=conference. I have tried to standardize them somewhat.
