### ISSUE TITLE
Add custom navigation for deep pages

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#7]
On the current website, I find deep sections with many pages (e.g. all pages of the [TDWG 2022 conference](https://www.tdwg.org/conferences/2022/)) not very accessible or customizable. The child pages can only be shown as tiles on the bottom of the page: https://www.tdwg.org/conferences/2022/#additional%20information

I suggest to facilitate navigation for those section by assigning a **custom top navigation**. See a live example at https://tdwg.github.io/website-jekyll/conferences/2022/

<img width="1139" alt="Screenshot 2022-11-13 at 21 35 35" src="https://user-images.githubusercontent.com/600993/201543439-26b0e07c-a173-4cdf-9740-150ac39068c9.png">

**Advantages**

- Easier navigation for the user
- Pages of a conference are easily identifiable as being part of TDWG 2022 because of the shared top navigation
- User can get back to the main site by clicking the logo 
- Much easier to customize for editors
- Much easier to group related pages in a dropdown (e.g. my attempt to group pages related to submissions)
- No need to assign page numbers, since the order can be defined in the navigation, see https://github.com/tdwg/website-jekyll/blob/main/_data/navigation-tdwg-2022.yaml

 @gkampmeier I hope you like this feature/suggestion 😄

**Comment by gkampmeier** [comment]
@peterdesmet looks great! Thank you!  P.S. Assigning page numbers was painful when you ran out of room.

**Comment by stanblum** [comment]
I like the menus, too.

-- 
Sent from my phone.

**Comment by peterdesmet** [comment]
This is now implemented for:

https://www.tdwg.org/conferences/2022/
https://www.tdwg.org/conferences/2021/
https://www.tdwg.org/conferences/2020/
