### ISSUE TITLE
Create controlled list of tags/categories to be used for posts

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#8]
I like that categories are actually functional as filters--in this case, I'm not sure what we would use tags for if they don't have this functionality. We need to develop and post a (working) controlled vocabulary available to website developers as a reminder of what can/should be used.

_Originally posted by @gkampmeier in https://github.com/tdwg/website-jekyll/issues/5#issuecomment-1312854933_

**Comment by ben-norton** [comment]
Say No to Tags!

**Comment by ben-norton** [comment]
Tags are pointless if not tightly controlled.

**Comment by stanblum** [comment]
If they aren't a part of some function, like an index or something, I don't
understand their purpose.

**Comment by peterdesmet** [comment]
Tags would be used to filter posts, see e.g. https://oscibio.inbo.be/blog/?tag=GBIF
Some of the current TDWG blog posts do have tags… but we don’t have to use them 🤷‍♂️

**Comment by gkampmeier** [comment]
IMHO, if tags have actual functionality (click on one to bring up similarly themed content) figuring out how they can be used effectively and communicating the vocabulary that should be used can enhance the experience of those using the website. As @peterdesmet points out, this can be especially useful in a blog or news setting.

**Comment by peterdesmet** [comment]
See #5, tags are only used for blog posts and I tried to have them somewhat controlled.
