### ISSUE TITLE
Standards overview page

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#9]
The website currently has a standards overview page: https://www.tdwg.org/standards/

- I think this page (or at least its URL) should be preserved, as their are probably many incoming links
- I don't think listing all standards in the menu is workable (see [screenshot](https://user-images.githubusercontent.com/600993/201647737-3fadab80-8e6b-4efc-8557-e72350f03eb5.png))
- Could replicate the listing of standards as cards, but it requires some work. Also not entirely sure the cards are that easy to scan for users

I therefore propose:

- A simple overview page of the standards (no cards, just links): https://tdwg.github.io/website-jekyll/standards/
- Listing the most popular standards in the dropdown, for easier access

<img width="188" alt="Screenshot 2022-11-14 at 12 40 36" src="https://user-images.githubusercontent.com/600993/201651137-e78be339-d0a1-43c4-bf56-f733bf42eb03.png">

@stanblum and co: thoughts?

**Comment by gkampmeier** [comment]
@peterdesmet The TAG will be undergoing a review and major reorganization of how the standards pages are put together in the coming year.  You might talk with @baskaufs before going too far with this.

**Comment by peterdesmet** [comment]
Thanks! Knowing that things will likely change is in fact a vote for my simple solution 😊:

- Keep standard pages as is
- Get rid of tags
- Have a standards overview page where the standards are listed manually (rather than automatically based on tags). Makes it easy to change/customize later

**Comment by peterdesmet** [comment]
@baskaufs are you ok with that?

**Comment by ben-norton** [comment]
@baskaufs For what my two cents are worth, I support all of @peterdesmet recommendations with one small set of revisions.
Drop the navigation column on the right.  Add the four categories to the top of the page. Add a 'return to top button on the bottom right. List the standards in 2-3 columns-based on screensize using the column-count css property (https://developer.mozilla.org/en-US/docs/Web/CSS/column-count).
Here's why. Using columns to list the standards is much more efficient than scrolling and linebreaks should always be avoided when possible. If you drop the right-side navigation, the main container will be wider. Since you're listing standards in columns and dropping the cards, you most likely don't need the right navigation anyways. Adding anchor links to the categories at the top is optional, but preserves the right-side navigation component, just in a revised fashion. If a visitor uses the right-side navigation, they most likely only click it once per page visit. Therefore, you can replace it with a top navigation row.

With that said, this may be entirely too much work using markdown in GitHub. If it is, let me know. It'll help me curtail future suggestions.

**Comment by peterdesmet** [comment]
@ben-norton do you mean a column layout like this: https://oscibio.inbo.be/blog/ (here using cards)?

A column layout (with cards) can be implemented, but I sometimes find them harder to scan, because you need to scan left right and top bottom.

**Comment by baskaufs** [comment]
I don't have a strong preference on layout and will defer to those with more experience in web design. I agree with @ben-norton  about getting rid of the right navigation -- it doesn't add anything and takes up real estate. 

If manual layout is not to terrible to set up, then get rid of the tags. I think that would give more control and make the page easier to maintain after the initial set-up. I think we are currently hampered by the fact that managing the layout via tags is obscure to potential page editors. 

If we make @peterdesmet's proposed change, then the page could be laid out with the most commonly used stuff higher up. 

The main axe that I have to grind at the moment is to get rid of the draft standards category and both items listed there. I gave this reason in an email earlier today and to briefly recap: we don't list any other standards that are in draft here; the only reason these are here is as a holdover from previous web management systems. GGBN is not on track to become a standard and Collections Description has been replaced with Latimer Core, which is nearly ratified. So get them out of here and stop confusing people by putting things here that are not actually anywhere on the standards track.

**Comment by peterdesmet** [comment]
> right navigation

Now removed, although we didn't really need the real estate 😄 : https://tdwg.github.io/website-jekyll/

I also removed the dropdown from the top menu, so it just says "standards" (like current website)

> So get them out of here

Draft standards now removed from the page. @baskaufs Should we also remove their pages? https://www.tdwg.org/standards/ggbn/ and https://www.tdwg.org/standards/ncd/ or do they need to remain there (not linked)?

> If manual layout is not to terrible to set up, then get rid of the tags. I think that would give more control and make the page easier to maintain after the initial set-up. I think we are currently hampered by the fact that managing the layout via tags is obscure to potential page editors.

Agree, which is why I propose a purposefully simple setup. This could be done in either two ways:

1. Manually maintaining the list on the markdown page. Easy to understand, limited customization options
2. Manually maintaining the list as csv/yaml in the `_data` dir (cf. how the [top navigation](https://github.com/tdwg/website-jekyll/blob/main/_data/navigation.yaml)). The fact that it is maintained there can be mentioned in a comment on the markdown page. Maintaining it as such allows for more customization on how it is displayed (e.g. as cards). @gkampmeier you put a thumbs up on https://github.com/tdwg/website-jekyll/issues/9#issuecomment-1313959000, but I don't know if it was to favour cards or a simple vertical list?

I think we should use the same choice for the **standards** and **community** overview page.

**Comment by gkampmeier** [comment]
@peterdesmet the cards are distracting--the eye doesn't know where to look first.  For standards pages or news where order is not important, this may not matter as much (can choose what attracts your eye), but if you're looking for something, or have something that includes a sequence or directions, having a right column navigation is essential.

**Comment by peterdesmet** [comment]
@gkampmeier agree, which is why on the Jekyll side, the right hand navigation (table of content) is enabled by default on all pages. The question is then, where _do_ we want cards?

- They are a default feature for posts (with tags to filter them).
- They could be implemented for standards (as they currently are), but then I would show them all together, rather than under 3 headings. Alternatively, we use a simple overview: https://tdwg.github.io/website-jekyll/standards/
- They could be implemented for interest groups and working groups (as they currently are), but having a more hierarchical overview of IG and their WG would be more beneficial in my opinion. I'll create a separate issue for that one.

**Comment by gkampmeier** [comment]
@peterdesmet given the restructuring of the [menus at the top of the page](https://tdwg.github.io/website-jekyll/conferences/2022/), I'm not sure we need cards for conferences anymore.  

The other big place we use them (other than community and standards pages) is call outs on some about pages for [translations](https://www.tdwg.org/about/diversity-inclusion/), although truthfully those would probably be easier to find/identify as indicated by the link at the top "Translations: FR" given that it would be great to have these pages in many other languages and this would quickly appear [redundant](https://www.tdwg.org/conferences/2021/#additional%20information) (see last three cards). 

[Terms of Use](https://www.tdwg.org/about/terms-of-use/) page has the story of [Copyright Infringement](https://www.tdwg.org/about/terms-of-use/copyright-infringement/). Arguably this is a good use of a card as it highlights a special story that would be hidden/lost by putting a simple link in the text or somehow linked in a menu.  

Upshot is that I think there is a place for judicious use of cards to highlight or tantalize the reader with content, but a number of places where these now appear on our site are superfluous.

**Comment by baskaufs** [comment]
> Draft standards now removed from the page. @baskaufs Should we also remove their pages? https://www.tdwg.org/standards/ggbn/ and https://www.tdwg.org/standards/ncd/ or do they need to remain there (not linked)?

For now maybe leave them. It might be useful to look at them when constructing some history. (could dig them out of the git history, but easier to just look at the unlinked pages)

**Comment by peterdesmet** [comment]
Updated overview page available at https://dev.tdwg.org/standards/, the list is defined at https://github.com/tdwg/website/blob/jekyll/standards/index.md?plain=1#L13-L35

ggbn and ncd are not listed, but their pages remain.
